apiVersion: v2
name: tome-tracker
description: A Helm chart for the TomeTracker app
type: application

dependencies:
  - repository: file://./charts/mariadb
    version: 11.8.0
    name: mariadb

version: 0.1.0

appVersion: "latest"
