# Default values for mariadb.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: registry.suse.com/suse/mariadb
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3306

global:
  # The name of the secret to use for the root password.
  mariadbSecretName: ""

resources: {}

persistence:
  enabled: true
  size: 8Gi
  # storageClassName: ""